obj-$(CONFIG_MACH_OPERAUL) += board-operaul.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-audio.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-camera.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-gpiomux.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-keypad.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-mmc.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-pmic.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-regulator.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-rfkill.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-storage.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-wifi.o
obj-$(CONFIG_MACH_OPERAUL) += display/

